### PR TITLE
Card routing

### PR DESCRIPTION
**Pull request by Shehan29**

### CODE REVIEW

**Review by AkshayPall — COMMENTED** [review]
So it routed correctly but
1) does not save updates to view
2) when a view is selected, I can't select the source doc for editing. IT instead collapses the source doc (cuz it had to be open to select the view in the first place).

Will we address 1 & 2 in separate PRs?

**Review by AkshayPall — CHANGES_REQUESTED** [review]
Also, I found a bug in the card view where rearranging the tags doesn't re-render the display.

1) Just add enough rags for school (here i have 5)
2) add them
3) play around with the order.

Should be a simple fix.

**Comment by AkshayPall** [comment]
`Hello` should not appear in the first card at all
Screen Shot 2021-01-29 at 11 15 25 AM

**Comment by Shehan29** [comment]
> So it routed correctly but
> 
> 1. does not save updates to view
> 2. when a view is selected, I can't select the source doc for editing. IT instead collapses the source doc (cuz it had to be open to select the view in the first place).
> 
> Will we address 1 & 2 in separate PRs?

1. Yeah we need to do saves. Let's do this in a separate PR.
2. The inability to select the source doc after clicking a view is a bug in the Navigator. Arv or I can fix this in a separate PR as well (along with making it more visible that a view was selected)

**Comment by Shehan29** [comment]
- Saving now works with Ctrl/Cmd + S
- The cards not updating was a bug in rich markdown which is now fixed and merged

**Review by AkshayPall — APPROVED** [review]
🚀

**Pull request merged**
